### ISSUE TITLE
Create payoff / Abrechnung durchführen

### ISSUE THREAD

**Issue by natrius** [SFTtech/abrechnung#158] opened 2023-01-13 12:33 UTC
In a flat, for example, a button would be nice to create a payoff, so everbody gets a clear info on what they should pay and the balance should be back to 0. 
Especially useful for a shared flat or at the end of a holiday for example.

**Comment by TheJJ** [comment] 2023-01-13 15:42
I think that's a duplicate of #19 :)

**Closed as completed by TheJJ** 2023-01-13 15:42 UTC
Labels: duplicate
